// https://docs.cypress.io/api/introduction/api.html

describe('My First Test', () => {
  it('Visits the app root url', () => {
    cy.viewport(1536, 754)
   cy.visit('http://localhost:4040/login')
   cy.get('body > #app > .grey').click()
   cy.get('div > .card > .card-content > .input-field > #email').click()
   cy.get('div > .card > .card-content > .input-field > #email').type('karmbobday@gmail.com')
   cy.get('body > #app > .grey').click()
   cy.get('div > .card > .card-content > .input-field > #password').click()
   cy.get('div > .card > .card-content > .input-field > #password').type('123456')
   cy.get('div > .card > .card-action > div > .btn').click()
   cy.get('div > .sidenav > a:nth-child(4) > li > .waves-effect').click()
   cy.get('div > .form > .input-field > .select-wrapper > .dropdown-trigger').click()
   cy.contains('Девушка').click()
   cy.get('.app-page > div > .form > .input-field > #amount').click()
   cy.get('.app-page > div > .form > .input-field > #amount').type('16587956')
   cy.get('.app-page > div > .form > .input-field:nth-child(5) > label').click()
   cy.get('.app-page > div > .form > .input-field > #description').type('Это расходы на девушку')
   cy.get('.app-content > .app-page > div > .form > .btn').click()
   cy.wait(3000)
   cy.get('.app-page > div > .form > .input-field > #amount').clear()
   cy.get('.app-page > div > .form > .input-field > #amount').type('1658')
   cy.get('.app-page > div > .form > .input-field > #description').clear()
   cy.get('.app-page > div > .form > .input-field > #description').type('Это расходы на девушку')
   cy.get('.app-content > .app-page > div > .form > .btn').click()
  })
})
